companies:
- id: stripe
  name: Stripe
  enabled: true
  adapter: greenhouse
  handle: stripe
- id: anthropic
  name: Anthropic
  enabled: true
  adapter: greenhouse
  handle: anthropic
- id: airbnb
  name: Airbnb
  enabled: true
  adapter: greenhouse
  handle: airbnb
- id: doordash
  name: DoorDash
  enabled: true
  adapter: greenhouse
  handle: doordashusa
- id: hubspot
  name: HubSpot
  enabled: true
  adapter: greenhouse
  handle: hubspot
- id: datadog
  name: Datadog
  enabled: true
  adapter: greenhouse
  handle: datadog
- id: okta
  name: Okta
  enabled: true
  adapter: greenhouse
  handle: okta
- id: twilio
  name: Twilio
  enabled: true
  adapter: greenhouse
  handle: twilio
- id: toast
  name: Toast
  enabled: true
  adapter: greenhouse
  handle: toast
- id: linkedin
  name: LinkedIn
  enabled: true
  adapter: smartrecruiters
  handle: LinkedIn3
- id: databricks
  name: Databricks
  enabled: true
  adapter: greenhouse
  handle: databricks
- id: cloudflare
  name: Cloudflare
  enabled: true
  adapter: greenhouse
  handle: cloudflare
- id: coinbase
  name: Coinbase
  enabled: true
  adapter: greenhouse
  handle: coinbase
- id: mongodb
  name: MongoDB
  enabled: true
  adapter: greenhouse
  handle: mongodb
- id: robinhood
  name: Robinhood
  enabled: true
  adapter: greenhouse
  handle: robinhood
- id: lyft
  name: Lyft
  enabled: true
  adapter: greenhouse
  handle: lyft
- id: roblox
  name: Roblox # Does not sponsor H1B
  enabled: false
  adapter: greenhouse
  handle: roblox
- id: pinterest
  name: Pinterest
  enabled: true
  adapter: greenhouse
  handle: pinterestjobadvertisements
- id: block
  name: Block
  enabled: true
  adapter: greenhouse
  handle: block
- id: instacart
  name: Instacart
  enabled: true
  adapter: greenhouse
  handle: instacart
- id: elastic
  name: Elastic
  enabled: true
  adapter: greenhouse
  handle: elastic
- id: affirm
  name: Affirm
  enabled: true
  adapter: greenhouse
  handle: affirm
- id: verkada
  name: Verkada
  enabled: true
  adapter: greenhouse
  handle: verkada
- id: gusto
  name: Gusto
  enabled: true
  adapter: greenhouse
  handle: gusto
- id: netskope
  name: Netskope
  enabled: true
  adapter: greenhouse
  handle: netskope
- id: palantir
  name: Palantir
  enabled: false
  adapter: lever
  handle: palantir
- id: shield-ai
  name: Shield AI
  enabled: false
  adapter: lever
  handle: shieldai
- id: spotify
  name: Spotify
  enabled: false
  adapter: lever
  handle: spotify
- id: zoox
  name: Zoox
  enabled: false
  adapter: lever
  handle: zoox
- id: servicenow
  name: ServiceNow
  enabled: true
  adapter: smartrecruiters
  handle: ServiceNow
- id: wise
  name: Wise
  enabled: true
  adapter: smartrecruiters
  handle: Wise
